#!/bin/bash
# Fomenko A V (c)

#=======FUNCTIONS===============================================================
BACKUP()
{
    echo "BACKUP"
    echo $sp
        
    read -p "Input image name (use machine serial number; example: 10049.iso): " image_name

    echo $sp
    echo "Backup start"
    sudo dd if=$device of=$image_name bs=4M status=progress; sync
    echo "Backup done"
    echo $sp
}

UPGRADE()
{
    echo "UPGRADE"
    echo $sp
    i=0

    for file in *.ddi; do
        echo $i "-" $file
        hash_list[$i]=$file
        ((i++))
    done

    flag_input=0
    while [ $flag_input -eq 0 ]
    do
        read -p "Select image number: " selction_image

        if [ -v hash_list[selction_image] ]; then
            flag_input=1
        fi
    done

    IMAGE=${hash_list[$selction_image]}
    echo $sp
    echo "Selected image:"
    echo $IMAGE

    echo $sp
    echo "Upgrade start"
    sudo dd if=$IMAGE of=$device bs=4M status=progress; sync
    echo "Upgrade done"
    echo $sp
}
#=======END FUNCTIONS===========================================================

sp="==========================================================================="

echo "Disk list OUTPUT"
echo $sp
lsblk
echo $sp

read -p "Input device name (example: /dev/sdX): " device

flag1=0

while [ $flag1 -eq 0 ]
do
    read -p "Make backup (B), upgrade (U) or backup and upgrade (S)? " upg

    case $upg in
        B|b)
            BACKUP
            flag1=1
            ;;
        U|u)
            UPGRADE
            flag1=1
            ;;
        S|s) 
            echo "BACKUP and UPGRADE"
            BACKUP
            UPGRADE
            flag1=1
            ;;
        *)
            echo "Wrong choice, retry..."
            sleep 2
            ;;
    esac
done
